// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order/order.proto

package order

import (
	context "context"
	fmt "fmt"
	product "github.com/drhelius/grpc-demo-proto/product"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Order struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Date                 int64              `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	Products             []*product.Product `protobuf:"bytes,4,rep,name=products,proto3" json:"products,omitempty"`
	Ip                   string             `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Order) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *Order) GetProducts() []*product.Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *Order) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type CreateOrderReq struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderReq) Reset()         { *m = CreateOrderReq{} }
func (m *CreateOrderReq) String() string { return proto.CompactTextString(m) }
func (*CreateOrderReq) ProtoMessage()    {}
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{1}
}

func (m *CreateOrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderReq.Unmarshal(m, b)
}
func (m *CreateOrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderReq.Marshal(b, m, deterministic)
}
func (m *CreateOrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderReq.Merge(m, src)
}
func (m *CreateOrderReq) XXX_Size() int {
	return xxx_messageInfo_CreateOrderReq.Size(m)
}
func (m *CreateOrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderReq proto.InternalMessageInfo

func (m *CreateOrderReq) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type CreateOrderResp struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderResp) Reset()         { *m = CreateOrderResp{} }
func (m *CreateOrderResp) String() string { return proto.CompactTextString(m) }
func (*CreateOrderResp) ProtoMessage()    {}
func (*CreateOrderResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{2}
}

func (m *CreateOrderResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderResp.Unmarshal(m, b)
}
func (m *CreateOrderResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderResp.Marshal(b, m, deterministic)
}
func (m *CreateOrderResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderResp.Merge(m, src)
}
func (m *CreateOrderResp) XXX_Size() int {
	return xxx_messageInfo_CreateOrderResp.Size(m)
}
func (m *CreateOrderResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderResp proto.InternalMessageInfo

func (m *CreateOrderResp) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadOrderReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadOrderReq) Reset()         { *m = ReadOrderReq{} }
func (m *ReadOrderReq) String() string { return proto.CompactTextString(m) }
func (*ReadOrderReq) ProtoMessage()    {}
func (*ReadOrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{3}
}

func (m *ReadOrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadOrderReq.Unmarshal(m, b)
}
func (m *ReadOrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadOrderReq.Marshal(b, m, deterministic)
}
func (m *ReadOrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadOrderReq.Merge(m, src)
}
func (m *ReadOrderReq) XXX_Size() int {
	return xxx_messageInfo_ReadOrderReq.Size(m)
}
func (m *ReadOrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadOrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadOrderReq proto.InternalMessageInfo

func (m *ReadOrderReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadOrderResp struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadOrderResp) Reset()         { *m = ReadOrderResp{} }
func (m *ReadOrderResp) String() string { return proto.CompactTextString(m) }
func (*ReadOrderResp) ProtoMessage()    {}
func (*ReadOrderResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{4}
}

func (m *ReadOrderResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadOrderResp.Unmarshal(m, b)
}
func (m *ReadOrderResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadOrderResp.Marshal(b, m, deterministic)
}
func (m *ReadOrderResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadOrderResp.Merge(m, src)
}
func (m *ReadOrderResp) XXX_Size() int {
	return xxx_messageInfo_ReadOrderResp.Size(m)
}
func (m *ReadOrderResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadOrderResp.DiscardUnknown(m)
}

var xxx_messageInfo_ReadOrderResp proto.InternalMessageInfo

func (m *ReadOrderResp) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func init() {
	proto.RegisterType((*Order)(nil), "order.Order")
	proto.RegisterType((*CreateOrderReq)(nil), "order.CreateOrderReq")
	proto.RegisterType((*CreateOrderResp)(nil), "order.CreateOrderResp")
	proto.RegisterType((*ReadOrderReq)(nil), "order.ReadOrderReq")
	proto.RegisterType((*ReadOrderResp)(nil), "order.ReadOrderResp")
}

func init() {
	proto.RegisterFile("order/order.proto", fileDescriptor_fa47a2077d8980ed)
}

var fileDescriptor_fa47a2077d8980ed = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcd, 0x4e, 0x2a, 0x31,
	0x14, 0xce, 0x0c, 0x3f, 0xb9, 0x1c, 0xb8, 0x5c, 0x6e, 0xef, 0x85, 0x4c, 0x26, 0xc6, 0x60, 0x57,
	0x18, 0x65, 0x1a, 0xc1, 0x95, 0x4b, 0x5d, 0xb9, 0x52, 0xc7, 0x9d, 0xbb, 0x32, 0x6d, 0x86, 0x26,
	0x30, 0xad, 0x6d, 0x61, 0x63, 0xd8, 0xf8, 0x0a, 0xbe, 0x86, 0x6f, 0xe3, 0x2b, 0xf8, 0x20, 0x86,
	0x76, 0x24, 0x80, 0x2e, 0xdc, 0x4c, 0x7b, 0xbe, 0x73, 0xce, 0xf7, 0x93, 0x29, 0xfc, 0x95, 0x9a,
	0x71, 0x4d, 0xdc, 0x37, 0x51, 0x5a, 0x5a, 0x89, 0x6a, 0xae, 0x88, 0x0f, 0x72, 0x29, 0xf3, 0x19,
	0x27, 0x54, 0x09, 0x42, 0x8b, 0x42, 0x5a, 0x6a, 0x85, 0x2c, 0x8c, 0x1f, 0x8a, 0xbb, 0x4a, 0x4b,
	0xb6, 0xc8, 0x2c, 0x29, 0x4f, 0x0f, 0xe3, 0x15, 0xd4, 0x6e, 0xd6, 0xdb, 0xa8, 0x0d, 0xa1, 0x60,
	0x51, 0xd0, 0x0f, 0x06, 0x8d, 0x34, 0x14, 0x0c, 0x21, 0xa8, 0x16, 0x74, 0xce, 0xa3, 0xd0, 0x21,
	0xee, 0xbe, 0xc6, 0x18, 0xb5, 0x3c, 0xaa, 0xf4, 0x83, 0x41, 0x25, 0x75, 0x77, 0x74, 0x0a, 0xbf,
	0x4a, 0x46, 0x13, 0x55, 0xfb, 0x95, 0x41, 0x73, 0xd4, 0x49, 0x3e, 0x25, 0x6e, 0xfd, 0x99, 0x6e,
	0x26, 0x9c, 0x8a, 0x8a, 0x6a, 0xa5, 0x8a, 0xc2, 0xe7, 0xd0, 0xbe, 0xd2, 0x9c, 0x5a, 0xee, 0x4c,
	0xa4, 0xfc, 0x11, 0x61, 0xf0, 0x71, 0x9c, 0x95, 0xe6, 0xa8, 0x95, 0xf8, 0xa4, 0xbe, 0xef, 0x5b,
	0xf8, 0x08, 0xfe, 0xec, 0x6c, 0x19, 0xb5, 0x6f, 0x1f, 0x1f, 0x42, 0x2b, 0xe5, 0x94, 0x6d, 0x68,
	0xf7, 0xfb, 0x63, 0xf8, 0xbd, 0xd5, 0x37, 0xea, 0x27, 0xba, 0xa3, 0xd7, 0x00, 0x5a, 0x0e, 0xb8,
	0xe7, 0x7a, 0x29, 0x32, 0x8e, 0xee, 0xa0, 0xee, 0x8d, 0xa0, 0x6e, 0x39, 0xbf, 0x9b, 0x26, 0xee,
	0x7d, 0x07, 0x1b, 0x85, 0xa3, 0xe7, 0xb7, 0xf7, 0x97, 0x10, 0xe1, 0x06, 0x59, 0x9e, 0xf9, 0x7f,
	0x79, 0xe1, 0x35, 0xd0, 0x35, 0x54, 0xd7, 0xc6, 0xd0, 0xbf, 0x72, 0x73, 0x3b, 0x45, 0xfc, 0xff,
	0x2b, 0x68, 0x14, 0xee, 0x39, 0xb2, 0x0e, 0x6a, 0x6f, 0xc8, 0xc8, 0x93, 0x60, 0xab, 0xcb, 0x93,
	0x87, 0xe3, 0x5c, 0xd8, 0xe9, 0x62, 0x92, 0x64, 0x72, 0x4e, 0x98, 0x9e, 0xf2, 0x99, 0x58, 0x18,
	0x92, 0x6b, 0x95, 0x0d, 0x19, 0x9f, 0xcb, 0xa1, 0x7b, 0x02, 0x7e, 0x63, 0x52, 0x77, 0xc5, 0xf8,
	0x23, 0x00, 0x00, 0xff, 0xff, 0x92, 0xc1, 0xe2, 0xf3, 0x60, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceClient interface {
	Create(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error)
	Read(ctx context.Context, in *ReadOrderReq, opts ...grpc.CallOption) (*ReadOrderResp, error)
}

type orderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceClient(cc grpc.ClientConnInterface) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) Create(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error) {
	out := new(CreateOrderResp)
	err := c.cc.Invoke(ctx, "/order.OrderService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) Read(ctx context.Context, in *ReadOrderReq, opts ...grpc.CallOption) (*ReadOrderResp, error) {
	out := new(ReadOrderResp)
	err := c.cc.Invoke(ctx, "/order.OrderService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
type OrderServiceServer interface {
	Create(context.Context, *CreateOrderReq) (*CreateOrderResp, error)
	Read(context.Context, *ReadOrderReq) (*ReadOrderResp, error)
}

// UnimplementedOrderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (*UnimplementedOrderServiceServer) Create(ctx context.Context, req *CreateOrderReq) (*CreateOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedOrderServiceServer) Read(ctx context.Context, req *ReadOrderReq) (*ReadOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).Create(ctx, req.(*CreateOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).Read(ctx, req.(*ReadOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "order.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _OrderService_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _OrderService_Read_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order/order.proto",
}
