// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account/account.proto

package account

import (
	context "context"
	fmt "fmt"
	order "github.com/drhelius/grpc-demo-proto/order"
	user "github.com/drhelius/grpc-demo-proto/user"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Account struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User                 *user.User     `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Orders               []*order.Order `protobuf:"bytes,3,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetUser() *user.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Account) GetOrders() []*order.Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type CreateAccountReq struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountReq) Reset()         { *m = CreateAccountReq{} }
func (m *CreateAccountReq) String() string { return proto.CompactTextString(m) }
func (*CreateAccountReq) ProtoMessage()    {}
func (*CreateAccountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{1}
}

func (m *CreateAccountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountReq.Unmarshal(m, b)
}
func (m *CreateAccountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountReq.Marshal(b, m, deterministic)
}
func (m *CreateAccountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountReq.Merge(m, src)
}
func (m *CreateAccountReq) XXX_Size() int {
	return xxx_messageInfo_CreateAccountReq.Size(m)
}
func (m *CreateAccountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountReq proto.InternalMessageInfo

func (m *CreateAccountReq) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type CreateAccountResp struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountResp) Reset()         { *m = CreateAccountResp{} }
func (m *CreateAccountResp) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResp) ProtoMessage()    {}
func (*CreateAccountResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{2}
}

func (m *CreateAccountResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResp.Unmarshal(m, b)
}
func (m *CreateAccountResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResp.Marshal(b, m, deterministic)
}
func (m *CreateAccountResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResp.Merge(m, src)
}
func (m *CreateAccountResp) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResp.Size(m)
}
func (m *CreateAccountResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResp proto.InternalMessageInfo

func (m *CreateAccountResp) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadAccountReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAccountReq) Reset()         { *m = ReadAccountReq{} }
func (m *ReadAccountReq) String() string { return proto.CompactTextString(m) }
func (*ReadAccountReq) ProtoMessage()    {}
func (*ReadAccountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{3}
}

func (m *ReadAccountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAccountReq.Unmarshal(m, b)
}
func (m *ReadAccountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAccountReq.Marshal(b, m, deterministic)
}
func (m *ReadAccountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAccountReq.Merge(m, src)
}
func (m *ReadAccountReq) XXX_Size() int {
	return xxx_messageInfo_ReadAccountReq.Size(m)
}
func (m *ReadAccountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAccountReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAccountReq proto.InternalMessageInfo

func (m *ReadAccountReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadAccountResp struct {
	Acount               *Account `protobuf:"bytes,1,opt,name=acount,proto3" json:"acount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAccountResp) Reset()         { *m = ReadAccountResp{} }
func (m *ReadAccountResp) String() string { return proto.CompactTextString(m) }
func (*ReadAccountResp) ProtoMessage()    {}
func (*ReadAccountResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{4}
}

func (m *ReadAccountResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAccountResp.Unmarshal(m, b)
}
func (m *ReadAccountResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAccountResp.Marshal(b, m, deterministic)
}
func (m *ReadAccountResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAccountResp.Merge(m, src)
}
func (m *ReadAccountResp) XXX_Size() int {
	return xxx_messageInfo_ReadAccountResp.Size(m)
}
func (m *ReadAccountResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAccountResp.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAccountResp proto.InternalMessageInfo

func (m *ReadAccountResp) GetAcount() *Account {
	if m != nil {
		return m.Acount
	}
	return nil
}

func init() {
	proto.RegisterType((*Account)(nil), "account.Account")
	proto.RegisterType((*CreateAccountReq)(nil), "account.CreateAccountReq")
	proto.RegisterType((*CreateAccountResp)(nil), "account.CreateAccountResp")
	proto.RegisterType((*ReadAccountReq)(nil), "account.ReadAccountReq")
	proto.RegisterType((*ReadAccountResp)(nil), "account.ReadAccountResp")
}

func init() {
	proto.RegisterFile("account/account.proto", fileDescriptor_d66906c5773c9d08)
}

var fileDescriptor_d66906c5773c9d08 = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x4a, 0xc3, 0x40,
	0x14, 0x26, 0x69, 0x49, 0xf1, 0x45, 0xfa, 0x33, 0xa0, 0xc6, 0x50, 0x24, 0x44, 0x17, 0x41, 0x69,
	0x06, 0xe3, 0x4e, 0x41, 0x50, 0x0f, 0x20, 0xa4, 0xb8, 0x11, 0x44, 0xd2, 0x64, 0x48, 0x07, 0xda,
	0x4c, 0x9c, 0x49, 0xba, 0x11, 0x37, 0x5e, 0xc1, 0x2b, 0x79, 0x03, 0xaf, 0xe0, 0x41, 0x24, 0x93,
	0x4c, 0x69, 0x83, 0xba, 0x79, 0xe1, 0xbd, 0xf7, 0x7d, 0xdf, 0xfb, 0x3e, 0x32, 0xb0, 0x17, 0xc5,
	0x31, 0x2b, 0xb3, 0x02, 0x37, 0x5f, 0x3f, 0xe7, 0xac, 0x60, 0xa8, 0xd7, 0xb4, 0xf6, 0x38, 0x65,
	0x2c, 0x5d, 0x10, 0x1c, 0xe5, 0x14, 0x47, 0x59, 0xc6, 0x8a, 0xa8, 0xa0, 0x2c, 0x13, 0x35, 0xcc,
	0x1e, 0x94, 0x82, 0x70, 0x5c, 0x95, 0x66, 0x30, 0x62, 0x3c, 0x21, 0x1c, 0xcb, 0x5a, 0x8f, 0xdc,
	0x67, 0xe8, 0xdd, 0xd4, 0x62, 0xa8, 0x0f, 0x3a, 0x4d, 0x2c, 0xcd, 0xd1, 0xbc, 0x9d, 0x50, 0xa7,
	0x09, 0x3a, 0x82, 0x6e, 0xc5, 0xb5, 0x74, 0x47, 0xf3, 0xcc, 0x00, 0x7c, 0x29, 0xf4, 0x20, 0x08,
	0x0f, 0xe5, 0x1c, 0x9d, 0x80, 0x21, 0x95, 0x84, 0xd5, 0x71, 0x3a, 0x9e, 0x19, 0xec, 0xfa, 0xb5,
	0xf0, 0x7d, 0x55, 0xc3, 0x66, 0xe7, 0x5e, 0xc3, 0xf0, 0x8e, 0x93, 0xa8, 0x20, 0xcd, 0x99, 0x90,
	0xbc, 0xa0, 0x53, 0x50, 0x09, 0xe4, 0x39, 0x33, 0x18, 0xfa, 0x2a, 0xa0, 0x42, 0x29, 0x80, 0x7b,
	0x0c, 0xa3, 0x16, 0x5f, 0xe4, 0x6d, 0xab, 0xae, 0x03, 0xfd, 0x90, 0x44, 0xc9, 0xc6, 0x89, 0x36,
	0xe2, 0x0a, 0x06, 0x5b, 0x08, 0x91, 0x23, 0x0f, 0x8c, 0xe8, 0x7f, 0x13, 0xcd, 0x3e, 0xf8, 0xd4,
	0xa0, 0xdf, 0xcc, 0xa6, 0x84, 0xaf, 0x68, 0x4c, 0xd0, 0x13, 0x18, 0xb5, 0x2d, 0x74, 0xb8, 0xa6,
	0xb5, 0x73, 0xda, 0xf6, 0x5f, 0x2b, 0x91, 0xbb, 0xe3, 0xf7, 0xaf, 0xef, 0x0f, 0x7d, 0xdf, 0x35,
	0xf1, 0xea, 0x5c, 0xfd, 0xde, 0x4b, 0x95, 0x1a, 0x4d, 0xa1, 0x5b, 0xd9, 0x45, 0x07, 0x6b, 0x85,
	0xed, 0x7c, 0xb6, 0xf5, 0xfb, 0x42, 0xe4, 0xae, 0x25, 0x85, 0x11, 0x1a, 0x6e, 0x08, 0xe3, 0x57,
	0x9a, 0xbc, 0xdd, 0x4e, 0x1e, 0xcf, 0x52, 0x5a, 0xcc, 0xcb, 0x99, 0x1f, 0xb3, 0x25, 0x4e, 0xf8,
	0x9c, 0x2c, 0x68, 0x29, 0x70, 0xca, 0xf3, 0x78, 0x92, 0x90, 0x25, 0x9b, 0xc8, 0x27, 0xa1, 0x38,
	0x33, 0x43, 0xb6, 0x17, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa2, 0x71, 0x22, 0x81, 0x85, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	Create(ctx context.Context, in *CreateAccountReq, opts ...grpc.CallOption) (*CreateAccountResp, error)
	Read(ctx context.Context, in *ReadAccountReq, opts ...grpc.CallOption) (*ReadAccountResp, error)
}

type accountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountServiceClient(cc grpc.ClientConnInterface) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) Create(ctx context.Context, in *CreateAccountReq, opts ...grpc.CallOption) (*CreateAccountResp, error) {
	out := new(CreateAccountResp)
	err := c.cc.Invoke(ctx, "/account.AccountService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Read(ctx context.Context, in *ReadAccountReq, opts ...grpc.CallOption) (*ReadAccountResp, error) {
	out := new(ReadAccountResp)
	err := c.cc.Invoke(ctx, "/account.AccountService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	Create(context.Context, *CreateAccountReq) (*CreateAccountResp, error)
	Read(context.Context, *ReadAccountReq) (*ReadAccountResp, error)
}

// UnimplementedAccountServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServiceServer struct {
}

func (*UnimplementedAccountServiceServer) Create(ctx context.Context, req *CreateAccountReq) (*CreateAccountResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedAccountServiceServer) Read(ctx context.Context, req *ReadAccountReq) (*ReadAccountResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Create(ctx, req.(*CreateAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Read(ctx, req.(*ReadAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _AccountService_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _AccountService_Read_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account/account.proto",
}
