// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product/product.proto

package product

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price                int32    `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f5dc4dd6fa6d7, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type CreateProductReq struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductReq) Reset()         { *m = CreateProductReq{} }
func (m *CreateProductReq) String() string { return proto.CompactTextString(m) }
func (*CreateProductReq) ProtoMessage()    {}
func (*CreateProductReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f5dc4dd6fa6d7, []int{1}
}

func (m *CreateProductReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductReq.Unmarshal(m, b)
}
func (m *CreateProductReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductReq.Marshal(b, m, deterministic)
}
func (m *CreateProductReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductReq.Merge(m, src)
}
func (m *CreateProductReq) XXX_Size() int {
	return xxx_messageInfo_CreateProductReq.Size(m)
}
func (m *CreateProductReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductReq proto.InternalMessageInfo

func (m *CreateProductReq) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type CreateProductResp struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductResp) Reset()         { *m = CreateProductResp{} }
func (m *CreateProductResp) String() string { return proto.CompactTextString(m) }
func (*CreateProductResp) ProtoMessage()    {}
func (*CreateProductResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f5dc4dd6fa6d7, []int{2}
}

func (m *CreateProductResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductResp.Unmarshal(m, b)
}
func (m *CreateProductResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductResp.Marshal(b, m, deterministic)
}
func (m *CreateProductResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductResp.Merge(m, src)
}
func (m *CreateProductResp) XXX_Size() int {
	return xxx_messageInfo_CreateProductResp.Size(m)
}
func (m *CreateProductResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductResp proto.InternalMessageInfo

func (m *CreateProductResp) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadProductReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadProductReq) Reset()         { *m = ReadProductReq{} }
func (m *ReadProductReq) String() string { return proto.CompactTextString(m) }
func (*ReadProductReq) ProtoMessage()    {}
func (*ReadProductReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f5dc4dd6fa6d7, []int{3}
}

func (m *ReadProductReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadProductReq.Unmarshal(m, b)
}
func (m *ReadProductReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadProductReq.Marshal(b, m, deterministic)
}
func (m *ReadProductReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadProductReq.Merge(m, src)
}
func (m *ReadProductReq) XXX_Size() int {
	return xxx_messageInfo_ReadProductReq.Size(m)
}
func (m *ReadProductReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadProductReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadProductReq proto.InternalMessageInfo

func (m *ReadProductReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadProductResp struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadProductResp) Reset()         { *m = ReadProductResp{} }
func (m *ReadProductResp) String() string { return proto.CompactTextString(m) }
func (*ReadProductResp) ProtoMessage()    {}
func (*ReadProductResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f9f5dc4dd6fa6d7, []int{4}
}

func (m *ReadProductResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadProductResp.Unmarshal(m, b)
}
func (m *ReadProductResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadProductResp.Marshal(b, m, deterministic)
}
func (m *ReadProductResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadProductResp.Merge(m, src)
}
func (m *ReadProductResp) XXX_Size() int {
	return xxx_messageInfo_ReadProductResp.Size(m)
}
func (m *ReadProductResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadProductResp.DiscardUnknown(m)
}

var xxx_messageInfo_ReadProductResp proto.InternalMessageInfo

func (m *ReadProductResp) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func init() {
	proto.RegisterType((*Product)(nil), "product.Product")
	proto.RegisterType((*CreateProductReq)(nil), "product.CreateProductReq")
	proto.RegisterType((*CreateProductResp)(nil), "product.CreateProductResp")
	proto.RegisterType((*ReadProductReq)(nil), "product.ReadProductReq")
	proto.RegisterType((*ReadProductResp)(nil), "product.ReadProductResp")
}

func init() {
	proto.RegisterFile("product/product.proto", fileDescriptor_5f9f5dc4dd6fa6d7)
}

var fileDescriptor_5f9f5dc4dd6fa6d7 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4b, 0x4e, 0xc3, 0x30,
	0x10, 0x55, 0x42, 0x3f, 0x62, 0x2a, 0x95, 0x62, 0xf1, 0x09, 0x51, 0x17, 0x91, 0xd9, 0x54, 0xa0,
	0xd6, 0xa2, 0xec, 0x90, 0x60, 0x01, 0x17, 0x40, 0xe9, 0x0e, 0x89, 0x45, 0x1a, 0x8f, 0x52, 0x4b,
	0x6d, 0x6c, 0xec, 0xb4, 0x1b, 0xc4, 0x86, 0x2b, 0x70, 0x25, 0x6e, 0xc0, 0x15, 0x38, 0x08, 0xaa,
	0x13, 0x57, 0x6d, 0x04, 0x0b, 0x56, 0xf6, 0xcc, 0xbc, 0x79, 0x1f, 0xd9, 0x70, 0xac, 0xb4, 0xe4,
	0xcb, 0xb4, 0x60, 0xd5, 0x39, 0x52, 0x5a, 0x16, 0x92, 0xb4, 0xab, 0x32, 0xec, 0x67, 0x52, 0x66,
	0x73, 0x64, 0x89, 0x12, 0x2c, 0xc9, 0x73, 0x59, 0x24, 0x85, 0x90, 0xb9, 0x29, 0x61, 0x14, 0xa1,
	0xfd, 0x58, 0x02, 0x49, 0x17, 0x7c, 0xc1, 0x03, 0x2f, 0xf2, 0x06, 0xfb, 0xb1, 0x2f, 0x38, 0x21,
	0xd0, 0xc8, 0x93, 0x05, 0x06, 0xbe, 0xed, 0xd8, 0x3b, 0x89, 0xa0, 0xc3, 0xd1, 0xa4, 0x5a, 0xa8,
	0x35, 0x49, 0xb0, 0x67, 0x47, 0xdb, 0x2d, 0x72, 0x04, 0x4d, 0xa5, 0x45, 0x8a, 0x41, 0x23, 0xf2,
	0x06, 0xcd, 0xb8, 0x2c, 0xe8, 0x1d, 0xf4, 0x1e, 0x34, 0x26, 0x05, 0x56, 0x62, 0x31, 0xbe, 0x90,
	0x0b, 0x70, 0x1e, 0xad, 0x68, 0x67, 0xdc, 0x1b, 0xb9, 0x08, 0x0e, 0xe5, 0x00, 0xf4, 0x1c, 0x0e,
	0x6b, 0xfb, 0x46, 0xd5, 0x0d, 0xd3, 0x08, 0xba, 0x31, 0x26, 0x7c, 0x4b, 0xa2, 0x8e, 0xb8, 0x85,
	0x83, 0x1d, 0x84, 0x51, 0xff, 0x71, 0x31, 0xfe, 0xf4, 0xa0, 0x5b, 0x35, 0x27, 0xa8, 0x57, 0x22,
	0x45, 0xf2, 0x0c, 0xad, 0xd2, 0x18, 0x39, 0xdb, 0xec, 0xd5, 0x93, 0x86, 0xe1, 0x5f, 0x23, 0xa3,
	0x68, 0xff, 0xfd, 0xeb, 0xfb, 0xc3, 0x3f, 0xa1, 0x1d, 0xb6, 0xba, 0x72, 0x4f, 0x78, 0xe3, 0x14,
	0xc9, 0x04, 0x1a, 0x6b, 0xc3, 0xe4, 0x74, 0xc3, 0xb0, 0x9b, 0x30, 0x0c, 0x7e, 0x1f, 0x18, 0x45,
	0x03, 0x4b, 0x4c, 0x48, 0x6f, 0x8b, 0x98, 0xbd, 0x0a, 0xfe, 0x76, 0x3f, 0x7c, 0xba, 0xcc, 0x44,
	0x31, 0x5b, 0x4e, 0x47, 0xa9, 0x5c, 0x30, 0xae, 0x67, 0x38, 0x17, 0x4b, 0xc3, 0x32, 0xad, 0xd2,
	0x21, 0xc7, 0x85, 0x1c, 0xda, 0xaf, 0xe1, 0x76, 0xa6, 0x2d, 0x5b, 0x5e, 0xff, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x4a, 0x09, 0xd0, 0xd5, 0x69, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductServiceClient interface {
	Create(ctx context.Context, in *CreateProductReq, opts ...grpc.CallOption) (*CreateProductResp, error)
	Read(ctx context.Context, in *ReadProductReq, opts ...grpc.CallOption) (*ReadProductResp, error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) Create(ctx context.Context, in *CreateProductReq, opts ...grpc.CallOption) (*CreateProductResp, error) {
	out := new(CreateProductResp)
	err := c.cc.Invoke(ctx, "/product.ProductService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) Read(ctx context.Context, in *ReadProductReq, opts ...grpc.CallOption) (*ReadProductResp, error) {
	out := new(ReadProductResp)
	err := c.cc.Invoke(ctx, "/product.ProductService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
type ProductServiceServer interface {
	Create(context.Context, *CreateProductReq) (*CreateProductResp, error)
	Read(context.Context, *ReadProductReq) (*ReadProductResp, error)
}

// UnimplementedProductServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProductServiceServer struct {
}

func (*UnimplementedProductServiceServer) Create(ctx context.Context, req *CreateProductReq) (*CreateProductResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedProductServiceServer) Read(ctx context.Context, req *ReadProductReq) (*ReadProductResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}

func RegisterProductServiceServer(s *grpc.Server, srv ProductServiceServer) {
	s.RegisterService(&_ProductService_serviceDesc, srv)
}

func _ProductService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).Create(ctx, req.(*CreateProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).Read(ctx, req.(*ReadProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "product.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ProductService_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _ProductService_Read_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product/product.proto",
}
